CityofPortland/streets-2035-app

- chart/values-test.yaml
> feat:Add noindex and nofollow headers to ingress

- src/components/street/Listing.vue
- src/composables/use-street.ts
> feat: Show street width on tiles and details

- src/pages/Streets.vue
> feat: Pull in street names with new tile layer

- src/components/address-suggest/AddressSuggest.vue
- src/components/address-suggest/Candidate.vue
- src/components/header/Header.vue
- src/components/map/Map.vue
- src/components/pager/Pager.vue
- src/components/panel/Panel.vue
- src/composables/cross-section/36.json
- src/composables/cross-section/40.json
- src/composables/cross-section/44.json
- src/composables/cross-section/50.json
- src/composables/cross-section/56.json
- src/composables/cross-section/60.json
- src/composables/cross-section/66.json
- src/composables/cross-section/76.json
- src/composables/cross-section/index.ts
- src/composables/use-street-classification.ts
- src/composables/use-street.ts
- src/pages/Home.vue
- src/pages/Streets.vue
- src/pages/street-type/StreetTypes.vue
> chore: Create JSON files for additional road widths

- package-lock.json
- package.json
- src/components/map/Map.vue
- src/composables/use-street.ts
- src/pages/Streets.vue
Adds extent querystring to have history of map navigation
Allows back button from other pages to view in map
Modifies map component to not override extent with zoom property
Ref: S2WM-44
> feat: Add extent querystring to map

- src/App.vue
- src/components/login/LoggedIn.vue
- src/components/login/SignIn.vue
- src/composables/use-login.ts
- src/pages/Login.vue
- src/pages/Logout.vue
- src/router/index.ts
- src/store/auth.ts
> feat: Add navigation guard for site

- src/pages/Streets.vue
> feat: Retain map settings when leaving and returning to map

- package-lock.json
- src/composables/use-street-classification.ts
- src/composables/use-street.ts
- src/pages/Streets.vue
Add pedestrian district feature layer to map.
Add toggle for pedestrian districts.
ref: S2WM-51
> feat: Add Pedestrian Districts to Map

- src/pages/Streets.vue
> feat: Add loading messages to Streets page.

- src/composables/use-street.ts
- src/pages/Streets.vue
> feat: Add error messages to streets page.

- src/components/address-suggest/AddressSuggest.vue
- src/pages/Streets.vue
Checks if array of values is not empty
Fixes required prop as a boolean type
Fixes taxLot query option
ref: S2WM-64
> fix: Check for address suggest values

- src/pages/public-improvements/Page.vue
> [S2WM-75] Changes to public improvement page

- src/components/street/Full.vue
- src/components/street/Section.vue
- src/components/street/Segment.vue
> [S2WM-79] Add indication there are no cross-sections

- src/pages/street-type/CivicCorridor.mdx
- src/pages/street-type/CivicMainStreet.mdx
- src/pages/street-type/CommunityCorridor.mdx
- src/pages/street-type/IndustrialRoad.mdx
- src/pages/street-type/LocalStreet.mdx
- src/pages/street-type/NeighborhoodCorridor.mdx
- src/pages/street-type/NeighborhoodMainStreet.mdx
> [S2WM-104] Update street type pages

- src/components/cross-section/Scorecard.vue
- src/components/cross-section/Scoresheet.vue
> [S2WM-99] Add disabled style to scorecards

- src/components/cross-section/Scorecard.vue
- src/components/cross-section/Scoresheet.vue
Adds move buttons and emits to scorecards
Emits handled by scoresheet which wraps option in reactive variables
ref: S2WM-99
> [S2WM-99] Add ability to move scorecards

- src/components/cross-section/Scorecard.vue
Change to show/hide language
ref: S2WM-118
> [S2WM-118] Change cross section opacity button text

- src/components/street/Full.vue
> [S2WM-119] Change segment width help text

- src/components/cross-section/Legend.vue
- src/pages/CapitalProjects.vue
> [S2WM-126] Change PDF link text

- src/App.vue
- src/components/street/Full.vue
- src/elements/anchor/Anchor.vue
- src/pages/Streets.vue
Updates order in nav menu and map settings
External anchor elements target _blank
ref: S2WM-131
> chore: Update ordering of street types

- src/pages/CapitalProjects.vue
> chore: Update cross section figure

- src/components/cross-section/Scorecard.vue
- src/composables/cross-section/index.ts
- src/elements/anchor/Anchor.vue
- src/pages/cross-section/List.vue
> feat: Update cross section page

- src/pages/cross-section/List.vue
> feat: Add intro to cross section viewer

- src/pages/public-improvements/House.vue
- src/pages/public-improvements/Page.vue
> chore: Change section colors

- src/components/cross-section/Scoresheet.vue
> chore: Update text for Greening on Cross-Sections

- src/pages/cross-section/List.vue
> chore: Update cross section intro text

- src/pages/development-improvements/Page.vue
> feat: Add Urban Forestry Link to Development Improvements Page

- src/pages/development-improvements/Page.vue
> chore: Fix page wording and remove unused file.

- src/composables/use-street-classification.ts
- src/pages/Streets.vue
> feat: Add the Freight Districts Layer to map

- src/pages/development-improvements/Page.vue
> chore: Update development improvement page text

- src/pages/street-type/CommunityCorridor.mdx
> fix: remove extra period

- chart/Chart.yaml
- package-lock.json
- package.json
- src/App.vue
- src/router/index.ts
> chore: Bump versions for release

- src/composables/sidewalk-tradeoff/database.json
- src/pages/Training.vue
- src/pages/development-improvements/Page.vue
- src/pages/sidewalk-tradeoff/Page.vue
- src/pages/sidewalk-tradeoff/Portion.vue
> chore: Final edits from emails

- src/components/footer/Footer.vue
- src/pages/street-type/Overview.vue
> chore: Two small text updates : street types & footer update

- src/composables/sidewalk-tradeoff/database.json
> fix: Update frontage standardWidth

- src/components/street/Full.vue
- src/store/classification.ts
Refactors classification link function to react to classification model changes.
ref: VERT-878
> fix: Classification label reactivity
